{% set name = "postgrest" %}
{% set version = "0.10.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 08eadc3d2ba40a4e1588affa016e815826ff76e8c4e2baba8d44d50b24d06d33

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - deprecation >=2.1.0
    - httpx >=0.23.0
    - pydantic >=1.9.0
    - strenum >=0.4.9

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - postgrest

about:
  home: https://github.com/supabase-community/postgrest-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PostgREST client for Python. This library provides an ORM interface to PostgREST
  description: |
    PostgREST client for Python. This library provides an ORM interface to PostgREST

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
